export default [
  { hex: "#F8BBD0", vuetify: "pink lighten-4" },
  { hex: "#283593", vuetify: "indigo darken-3" },
  { hex: "#B2DFDB", vuetify: "teal lighten-4" },
  { hex: "#C6FF00", vuetify: "lime accent-3" },
  { hex: "#01579B", vuetify: "light-blue darken-4" },
  { hex: "#B39DDB", vuetify: "deep-purple lighten-3" },
  { hex: "#FF5252", vuetify: "red accent-2" },
  { hex: "#004D40", vuetify: "teal darken-4" },
  { hex: "#EF6C00", vuetify: "orange darken-3" },
  { hex: "#8D6E63", vuetify: "brown lighten-1" },
  { hex: "#9FA8DA", vuetify: "indigo lighten-3" },
  { hex: "#263238", vuetify: "blue-grey darken-4" },
  { hex: "#FFF176", vuetify: "yellow lighten-2" },
  { hex: "#880E4F", vuetify: "pink darken-4" },
  { hex: "#2E7D32", vuetify: "green darken-3" },
  { hex: "#FFB74D", vuetify: "orange lighten-2" },
  { hex: "#D500F9", vuetify: "purple accent-3" },
  { hex: "#26A69A", vuetify: "teal lighten-1" },
  { hex: "#AED581", vuetify: "light-green lighten-2" },
  { hex: "#FBC02D", vuetify: "yellow darken-2" },
  { hex: "#0097A7", vuetify: "cyan darken-2" },
  { hex: "#D84315", vuetify: "deep-orange darken-3" },
  { hex: "#6D4C41", vuetify: "brown darken-1" },
  { hex: "#0D47A1", vuetify: "blue darken-4" },
];
